# Generated by Django 4.2.10 on 2024-02-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
